###DEV###
#全局默认配置文件,放在config目录下,springboot先加载config目录下的配置文件
server:
  tomcat:
    uri-encoding: UTF-8
spring:
  resources:
    #开发环境指定此值,以便加载swagger文档静态资源,其他环境不需要此值
    #static-locations: classpath:/
  redis:
    host: 172.18.149.81
    port: 6379
    password: Czr18665377170
    database: 0
    pool:
      max-idle: 300
      max-wait: 3000
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

freeapis:
  production_mode: Y
  enableAuth: Y
  requestLimit:
    enable: Y
    period: 60
    frequency:
      nonget: 20
      get: 30
  doc:
    enable: true
    enable-module-register: false
    name: 文档名称
    host: http://172.18.149.81/
    enable-db-register: true
  concurrent:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 10
    thread-name-prefix: FreeapisExecutor-
  core:
    mysql:
      url: jdbc:mysql://172.18.149.81:3306/airplay_auth?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: Czr18665377170
      initial-size: 20
      max-active: 200
      min-idle: 10
      max-wait: 30000